-- 商品ごとの一次情報根拠をAI判定から分離して保存する。
-- 既存データは更新せず、初期状態では公開根拠を0件のまま維持する。
-- 019_product_judgment_freshness.sql 適用後に実行する。

begin;

create table public.product_evidence (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  claim_type text not null,
  claim_text text not null,
  source_excerpt text,
  source_url text,
  source_name text,
  source_kind text not null,
  retrieved_at timestamptz,
  review_status text not null default 'ai_inferred',
  human_checked_at timestamptz,
  product_input_hash text not null,
  evidence_hash text not null,
  has_independent_comparison boolean not null default false,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_evidence_claim_type_check check (
    claim_type in (
      'manufacturing_origin',
      'company',
      'material_origin',
      'regional_brand',
      'other'
    )
  ),
  constraint product_evidence_claim_text_check check (
    length(btrim(claim_text)) between 1 and 300
  ),
  constraint product_evidence_source_excerpt_check check (
    source_excerpt is null
    or length(btrim(source_excerpt)) between 1 and 1000
  ),
  constraint product_evidence_source_name_check check (
    source_name is null
    or length(btrim(source_name)) between 1 and 160
  ),
  constraint product_evidence_source_kind_check check (
    source_kind in (
      'manufacturer',
      'public_body',
      'regional_body',
      'seller',
      'other'
    )
  ),
  constraint product_evidence_review_status_check check (
    review_status in ('ai_inferred', 'human_source_checked')
  ),
  constraint product_evidence_product_input_hash_check check (
    product_input_hash ~ '^[0-9a-f]{64}$'
  ),
  constraint product_evidence_evidence_hash_check check (
    evidence_hash ~ '^[0-9a-f]{64}$'
  ),
  constraint product_evidence_source_url_check check (
    source_url is null
    or (
      length(source_url) <= 2048
      and source_url ~* '^https://'
      and source_url !~ '[[:space:]]'
      and position('#' in source_url) = 0
      and split_part(source_url, '/', 3) !~ '@'
      and lower(source_url) !~ '^https://localhost([:/]|$)'
      and lower(source_url) !~ '^https://[^/]+\.localhost([:/]|$)'
      and lower(source_url) !~ '^https://[^/]+\.local([:/]|$)'
      and lower(source_url) !~ '^https://(0\.|10\.|127\.|169\.254\.|192\.168\.)'
      and lower(source_url) !~ '^https://172\.(1[6-9]|2[0-9]|3[01])\.'
      and lower(source_url) !~ '^https://\[(::1|fc[0-9a-f:]*|fd[0-9a-f:]*|fe80[0-9a-f:]*)\]'
    )
  ),
  constraint product_evidence_human_check_completeness check (
    (
      review_status = 'ai_inferred'
      and human_checked_at is null
    )
    or
    (
      review_status = 'human_source_checked'
      and source_url is not null
      and source_name is not null
      and source_excerpt is not null
      and retrieved_at is not null
      and human_checked_at is not null
      and retrieved_at <= human_checked_at
    )
  ),
  constraint product_evidence_publication_fields_check check (
    not is_public
    or (
      review_status = 'human_source_checked'
      and source_kind in ('manufacturer', 'public_body', 'regional_body')
      and source_url is not null
      and source_name is not null
      and source_excerpt is not null
      and retrieved_at is not null
      and human_checked_at is not null
    )
  ),
  constraint product_evidence_unique_content unique (
    product_id,
    claim_type,
    evidence_hash
  )
);

create index idx_product_evidence_product
  on public.product_evidence (product_id, updated_at desc);

create index idx_product_evidence_public
  on public.product_evidence (product_id, human_checked_at desc)
  where is_public;

alter table public.product_evidence enable row level security;
revoke all on table public.product_evidence from anon, authenticated;
revoke all on sequence public.product_evidence_id_seq from anon, authenticated;

create or replace function public.enforce_product_evidence_publication()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  current_product public.products%rowtype;
  latest_consistency_status text;
begin
  new.updated_at := now();

  if not new.is_public then
    return new;
  end if;

  select product.*
  into current_product
  from public.products product
  where product.id = new.product_id;

  if not found then
    raise exception '公開対象の商品が存在しません';
  end if;

  if not current_product.is_published
    or current_product.judgment_status <> 'current'
    or current_product.judgment_input_hash is null
    or current_product.judgment_input_hash is distinct from new.product_input_hash
  then
    raise exception '現在の商品内容と一致する根拠だけを公開できます';
  end if;

  select judgment.consistency_status
  into latest_consistency_status
  from public.judgments judgment
  where judgment.product_id = new.product_id
    and judgment.input_hash is not distinct from current_product.judgment_input_hash
  order by judgment.judged_at desc nulls last, judgment.id desc
  limit 1;

  if latest_consistency_status is distinct from 'passed' then
    raise exception '最新の整合性検査を通過した商品だけ根拠を公開できます';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_product_evidence_publication() from public;

create trigger product_evidence_publication_guard
before insert or update on public.product_evidence
for each row execute function public.enforce_product_evidence_publication();

create or replace function public.hide_stale_product_evidence()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  if old.judgment_input_hash is distinct from new.judgment_input_hash
    or old.is_published is distinct from new.is_published
    or old.judgment_status is distinct from new.judgment_status
  then
    update public.product_evidence evidence
    set
      is_public = false,
      updated_at = now()
    where evidence.product_id = new.id
      and evidence.is_public
      and (
        not new.is_published
        or new.judgment_status <> 'current'
        or new.judgment_input_hash is null
        or evidence.product_input_hash is distinct from new.judgment_input_hash
      );
  end if;

  return new;
end;
$$;

revoke all on function public.hide_stale_product_evidence() from public;

create trigger products_hide_stale_evidence
after update of judgment_input_hash, is_published, judgment_status
on public.products
for each row execute function public.hide_stale_product_evidence();

create or replace function public.get_public_product_evidence(p_product_id uuid)
returns table (
  id bigint,
  claim_type text,
  claim_text text,
  source_excerpt text,
  source_url text,
  source_name text,
  source_kind text,
  retrieved_at timestamptz,
  human_checked_at timestamptz,
  has_independent_comparison boolean,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select
    evidence.id,
    evidence.claim_type,
    evidence.claim_text,
    evidence.source_excerpt,
    evidence.source_url,
    evidence.source_name,
    evidence.source_kind,
    evidence.retrieved_at,
    evidence.human_checked_at,
    evidence.has_independent_comparison,
    evidence.updated_at
  from public.product_evidence evidence
  join public.products product on product.id = evidence.product_id
  where evidence.product_id = p_product_id
    and evidence.is_public
    and evidence.review_status = 'human_source_checked'
    and evidence.source_kind in ('manufacturer', 'public_body', 'regional_body')
    and product.is_published
    and product.judgment_status = 'current'
    and product.judgment_input_hash is not null
    and evidence.product_input_hash = product.judgment_input_hash
    and (
      select judgment.consistency_status
      from public.judgments judgment
      where judgment.product_id = product.id
        and judgment.input_hash is not distinct from product.judgment_input_hash
      order by judgment.judged_at desc nulls last, judgment.id desc
      limit 1
    ) = 'passed'
  order by evidence.claim_type, evidence.id;
$$;

revoke all on function public.get_public_product_evidence(uuid) from public;
grant execute on function public.get_public_product_evidence(uuid)
  to anon, authenticated, service_role;

commit;
